<?php

namespace Database\Seeders;

use App\Models\MenuItem;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MenuItemSeeder extends Seeder
{
    public function run(): void
    {
        $menuItems = [
            // Appetizers (category_id: 1)
            [
                'category_id' => 1,
                'name' => 'Truffle Arancini',
                'slug' => 'truffle-arancini',
                'description' => 'Crispy risotto balls infused with black truffle, served with garlic aioli',
                'price' => 14.00,
                'image_url' => 'https://images.unsplash.com/photo-1541529086526-db283c563270?w=400&h=300&fit=crop',
                'is_featured' => true,
                'is_vegetarian' => true,
                'preparation_time' => 15,
                'calories' => 320,
                'rating' => 4.8,
                'sort_order' => 1,
            ],
            [
                'category_id' => 1,
                'name' => 'Bruschetta Trio',
                'slug' => 'bruschetta-trio',
                'description' => 'Three varieties: classic tomato, mushroom & thyme, and avocado & feta',
                'price' => 12.00,
                'image_url' => 'https://images.unsplash.com/photo-1572695157363-bc31c5c7e26a?w=400&h=300&fit=crop',
                'is_featured' => false,
                'is_vegetarian' => true,
                'preparation_time' => 10,
                'calories' => 280,
                'rating' => 4.5,
                'sort_order' => 2,
            ],
            [
                'category_id' => 1,
                'name' => 'Calamari Fritti',
                'slug' => 'calamari-fritti',
                'description' => 'Tender calamari rings lightly battered and fried, with lemon herb dip',
                'price' => 16.00,
                'image_url' => 'https://images.unsplash.com/photo-1599921841143-0950658f9a8f?w=400&h=300&fit=crop',
                'is_featured' => true,
                'is_vegetarian' => false,
                'preparation_time' => 12,
                'calories' => 380,
                'rating' => 4.7,
                'sort_order' => 3,
            ],

            // Main Course (category_id: 2)
            [
                'category_id' => 2,
                'name' => 'Herb-Crusted Lamb Rack',
                'slug' => 'herb-crusted-lamb-rack',
                'description' => 'New Zealand lamb with rosemary crust, served with mint jus and roasted vegetables',
                'price' => 42.00,
                'image_url' => 'https://images.unsplash.com/photo-1544025162-d76694265947?w=400&h=300&fit=crop',
                'is_featured' => true,
                'is_vegetarian' => false,
                'preparation_time' => 35,
                'calories' => 650,
                'rating' => 4.9,
                'sort_order' => 1,
            ],
            [
                'category_id' => 2,
                'name' => 'Duck Confit',
                'slug' => 'duck-confit',
                'description' => 'Slow-cooked duck leg with crispy skin, cherry reduction, and parsnip puree',
                'price' => 38.00,
                'image_url' => 'https://images.unsplash.com/photo-1518492104633-130d0cc84637?w=400&h=300&fit=crop',
                'is_featured' => false,
                'is_vegetarian' => false,
                'preparation_time' => 30,
                'calories' => 720,
                'rating' => 4.6,
                'sort_order' => 2,
            ],
            [
                'category_id' => 2,
                'name' => 'Wild Mushroom Risotto',
                'slug' => 'wild-mushroom-risotto',
                'description' => 'Creamy Arborio rice with porcini, chanterelle, and truffle oil',
                'price' => 28.00,
                'image_url' => 'https://images.unsplash.com/photo-1476124369491-e7addf5db371?w=400&h=300&fit=crop',
                'is_featured' => true,
                'is_vegetarian' => true,
                'preparation_time' => 25,
                'calories' => 540,
                'rating' => 4.8,
                'sort_order' => 3,
            ],

            // Seafood (category_id: 3)
            [
                'category_id' => 3,
                'name' => 'Grilled Lobster Tail',
                'slug' => 'grilled-lobster-tail',
                'description' => 'Maine lobster with garlic butter, grilled asparagus, and lemon',
                'price' => 58.00,
                'image_url' => 'https://images.unsplash.com/photo-1551248429-40975aa4de74?w=400&h=300&fit=crop',
                'is_featured' => true,
                'is_vegetarian' => false,
                'preparation_time' => 25,
                'calories' => 480,
                'rating' => 4.9,
                'sort_order' => 1,
            ],
            [
                'category_id' => 3,
                'name' => 'Pan-Seared Scallops',
                'slug' => 'pan-seared-scallops',
                'description' => 'Jumbo scallops with cauliflower puree, crispy pancetta, and brown butter',
                'price' => 36.00,
                'image_url' => 'https://images.unsplash.com/photo-1626645738196-c2a7c87a8f58?w=400&h=300&fit=crop',
                'is_featured' => false,
                'is_vegetarian' => false,
                'preparation_time' => 20,
                'calories' => 380,
                'rating' => 4.7,
                'sort_order' => 2,
            ],
            [
                'category_id' => 3,
                'name' => 'Seafood Paella',
                'slug' => 'seafood-paella',
                'description' => 'Traditional Spanish rice with shrimp, mussels, clams, and saffron',
                'price' => 45.00,
                'image_url' => 'https://images.unsplash.com/photo-1534080564583-6be75777b70a?w=400&h=300&fit=crop',
                'is_featured' => true,
                'is_vegetarian' => false,
                'preparation_time' => 40,
                'calories' => 620,
                'rating' => 4.8,
                'sort_order' => 3,
            ],

            // Pasta (category_id: 4)
            [
                'category_id' => 4,
                'name' => 'Lobster Ravioli',
                'slug' => 'lobster-ravioli',
                'description' => 'Handmade ravioli filled with lobster, in a saffron cream sauce',
                'price' => 34.00,
                'image_url' => 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=400&h=300&fit=crop',
                'is_featured' => true,
                'is_vegetarian' => false,
                'preparation_time' => 25,
                'calories' => 520,
                'rating' => 4.8,
                'sort_order' => 1,
            ],
            [
                'category_id' => 4,
                'name' => 'Truffle Fettuccine',
                'slug' => 'truffle-fettuccine',
                'description' => 'Fresh fettuccine with black truffle cream and aged parmesan',
                'price' => 32.00,
                'image_url' => 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=400&h=300&fit=crop',
                'is_featured' => false,
                'is_vegetarian' => true,
                'preparation_time' => 20,
                'calories' => 580,
                'rating' => 4.6,
                'sort_order' => 2,
            ],
            [
                'category_id' => 4,
                'name' => 'Carbonara Classica',
                'slug' => 'carbonara-classica',
                'description' => 'Spaghetti with egg yolk, guanciale, pecorino romano, and black pepper',
                'price' => 26.00,
                'image_url' => 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=400&h=300&fit=crop',
                'is_featured' => false,
                'is_vegetarian' => false,
                'preparation_time' => 18,
                'calories' => 640,
                'rating' => 4.5,
                'sort_order' => 3,
            ],

            // Steaks (category_id: 5)
            [
                'category_id' => 5,
                'name' => 'Wagyu A5 Ribeye',
                'slug' => 'wagyu-a5-ribeye',
                'description' => 'Japanese A5 Wagyu ribeye, seared to perfection, with wasabi and ponzu',
                'price' => 95.00,
                'image_url' => 'https://images.unsplash.com/photo-1546241072-48010ad2862c?w=400&h=300&fit=crop',
                'is_featured' => true,
                'is_vegetarian' => false,
                'preparation_time' => 30,
                'calories' => 780,
                'rating' => 5.0,
                'sort_order' => 1,
            ],
            [
                'category_id' => 5,
                'name' => 'Filet Mignon',
                'slug' => 'filet-mignon',
                'description' => '8oz tenderloin with red wine reduction and truffle mashed potatoes',
                'price' => 52.00,
                'image_url' => 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=400&h=300&fit=crop',
                'is_featured' => true,
                'is_vegetarian' => false,
                'preparation_time' => 28,
                'calories' => 580,
                'rating' => 4.9,
                'sort_order' => 2,
            ],
            [
                'category_id' => 5,
                'name' => 'Tomahawk Ribeye',
                'slug' => 'tomahawk-ribeye',
                'description' => '32oz bone-in ribeye for two, with roasted bone marrow and chimichurri',
                'price' => 120.00,
                'image_url' => 'https://images.unsplash.com/photo-1546833998-877b37c2e5c6?w=400&h=300&fit=crop',
                'is_featured' => true,
                'is_vegetarian' => false,
                'preparation_time' => 45,
                'calories' => 1200,
                'rating' => 4.9,
                'sort_order' => 3,
            ],

            // Desserts (category_id: 6)
            [
                'category_id' => 6,
                'name' => 'Tiramisu',
                'slug' => 'tiramisu',
                'description' => 'Classic Italian dessert with mascarpone, espresso, and cocoa',
                'price' => 14.00,
                'image_url' => 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=400&h=300&fit=crop',
                'is_featured' => true,
                'is_vegetarian' => true,
                'preparation_time' => 10,
                'calories' => 420,
                'rating' => 4.8,
                'sort_order' => 1,
            ],
            [
                'category_id' => 6,
                'name' => 'Chocolate Lava Cake',
                'slug' => 'chocolate-lava-cake',
                'description' => 'Warm chocolate cake with molten center, served with vanilla ice cream',
                'price' => 16.00,
                'image_url' => 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=400&h=300&fit=crop',
                'is_featured' => true,
                'is_vegetarian' => true,
                'preparation_time' => 15,
                'calories' => 480,
                'rating' => 4.9,
                'sort_order' => 2,
            ],
            [
                'category_id' => 6,
                'name' => 'Crème Brûlée',
                'slug' => 'creme-brulee',
                'description' => 'Classic vanilla custard with caramelized sugar crust',
                'price' => 13.00,
                'image_url' => 'https://images.unsplash.com/photo-1470324161839-ce2bb6fa6bc3?w=400&h=300&fit=crop',
                'is_featured' => false,
                'is_vegetarian' => true,
                'preparation_time' => 12,
                'calories' => 360,
                'rating' => 4.6,
                'sort_order' => 3,
            ],

            // Beverages (category_id: 7)
            [
                'category_id' => 7,
                'name' => 'Signature Mojito',
                'slug' => 'signature-mojito',
                'description' => 'Fresh mint, lime, rum, and a splash of champagne',
                'price' => 16.00,
                'image_url' => 'https://images.unsplash.com/photo-1551538827-9c037cb4f32a?w=400&h=300&fit=crop',
                'is_featured' => false,
                'is_vegetarian' => true,
                'preparation_time' => 5,
                'calories' => 180,
                'rating' => 4.7,
                'sort_order' => 1,
            ],
            [
                'category_id' => 7,
                'name' => 'House Red Wine',
                'slug' => 'house-red-wine',
                'description' => 'Selected Cabernet Sauvignon from Napa Valley',
                'price' => 12.00,
                'image_url' => 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=400&h=300&fit=crop',
                'is_featured' => false,
                'is_vegetarian' => true,
                'preparation_time' => 2,
                'calories' => 120,
                'rating' => 4.5,
                'sort_order' => 2,
            ],
            [
                'category_id' => 7,
                'name' => 'Artisan Coffee',
                'slug' => 'artisan-coffee',
                'description' => 'Single-origin Ethiopian coffee, freshly brewed',
                'price' => 8.00,
                'image_url' => 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=300&fit=crop',
                'is_featured' => false,
                'is_vegetarian' => true,
                'preparation_time' => 5,
                'calories' => 5,
                'rating' => 4.6,
                'sort_order' => 3,
            ],
        ];

        foreach ($menuItems as $item) {
            MenuItem::create($item);
        }
    }
}
